### ISSUE TITLE
Facebook Login Doesn't work 

### ISSUE THREAD

**Issue by rmhulle** [hfreire/get-me-a-date#211]
Hi,

At first, Great Project!!!

When I turn on any channel, the facebook-login-for-bots can not enter facebook and get my token.

The facebook asks if I am the one who am making login attempts, I set ok to avoid problem of locking the account. But even so, the bot still can not get the token. 

So far I've tried restarting and even re-creating the container but it's not working.

Below is a copy of the App Log

2017-07-29T01:40:22,178+00:00 - info: 186.212.123.82 - "GET /channels" 200 19 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" "-"
2017-07-29T01:40:22,206+00:00 - info: 186.212.123.82 - "GET /stats?page=1&limit=15" 200 16 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" "-"
2017-07-29T01:40:22,209+00:00 - info: 186.212.123.82 - "GET /recommendations?page=0&limit=100&criteria={}&select=id&select=name&select=thumbnailUrl&select=isLike&select=isPass&select=isTrain&select=isHumanDecision&select=isMatch&select=photosSimilarityMean" 200 14 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" "-"
2017-07-29T01:40:22,213+00:00 - info: 186.212.123.82 - "GET /settings" 200 41 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" "-"
2017-07-29T01:40:29,118+00:00 - info: Started finding dates
2017-07-29T01:40:29,135+00:00 - info: Started updating stats
2017-07-29T01:40:29,156+00:00 - info: Finished updating stats
2017-07-29T01:40:29,157+00:00 - info: Finished finding dates (time = 0s)
2017-07-29T01:40:36,592+00:00 - info: 186.212.123.82 - "PUT /channels/happn" 200 20 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" "-"
2017-07-29T01:41:29,164+00:00 - info: Started finding dates
2017-07-29T01:41:29,195+00:00 - info: Started finding dates in Happn channel
2017-07-29T01:41:29,196+00:00 - info: Started checking recommendations from Happn channel
2017-07-29T01:41:29,200+00:00 - debug: Started Facebook Login for Happn channel
2017-07-29T01:42:48,826+00:00 - debug: Finished Facebook Login for Happn channel
2017-07-29T01:43:08,547+00:00 - error:  Error: Request Timed out
    at TimeOutError (/opt/get-me-a-date/node_modules/brakes/lib/TimeOutError.js:3:1)
    at Timeout.setTimeout (/opt/get-me-a-date/node_modules/brakes/lib/Circuit.js:103:16)
    at ontimeout (timers.js:386:14)
    at Timer.unrefdHandle (timers.js:492:5)
2017-07-29T01:43:08,830+00:00 - info: Finished checking recommendations from Happn channel (received = 0, skipped = 0, failed = 0)
2017-07-29T01:43:11,116+00:00 - info: Started checking updates from Happn 
2017-07-29T01:45:27,337+00:00 - debug: Started Facebook Login for Happn channel
2017-07-29T01:46:39,686+00:00 - debug: Finished Facebook Login for Happn channel
2017-07-29T01:46:39,801+00:00 - error:  Error: Request Timed out
    at TimeOutError (/opt/get-me-a-date/node_modules/brakes/lib/TimeOutError.js:3:1)
    at Timeout.setTimeout (/opt/get-me-a-date/node_modules/brakes/lib/Circuit.js:103:16)
    at ontimeout (timers.js:386:14)
    at Timer.unrefdHandle (timers.js:492:5)
2017-07-29T01:46:39,807+00:00 - info: Finished checking updates from Happn (matches = 0, messages = 0)
2017-07-29T01:46:39,808+00:00 - info: Finished finding dates in Happn channel
2017-07-29T01:46:39,810+00:00 - info: Started updating stats
2017-07-29T01:46:40,137+00:00 - info: Finished updating stats
2017-07-29T01:46:40,152+00:00 - info: Finished finding dates (time = 311s)
2017-07-29T01:48:01,778+00:00 - info: Started finding dates
2017-07-29T01:49:26,464+00:00 - info: Started finding dates in Tinder channel
2017-07-29T01:49:27,210+00:00 - info: Started checking recommendations from Tinder channel
2017-07-29T01:49:43,593+00:00 - debug: Started Facebook Login for Tinder channel
2017-07-29T01:51:19,488+00:00 - debug: Finished Facebook Login for Tinder channel
2017-07-29T01:51:19,601+00:00 - error:  Error: Request Timed out
    at TimeOutError (/opt/get-me-a-date/node_modules/brakes/lib/TimeOutError.js:3:1)
    at Timeout.setTimeout (/opt/get-me-a-date/node_modules/brakes/lib/Circuit.js:103:16)
    at ontimeout (timers.js:386:14)
    at Timer.unrefdHandle (timers.js:492:5)
2017-07-29T01:51:19,633+00:00 - info: Finished checking recommendations from Tinder channel (received = 0, skipped = 0, failed = 0)
2017-07-29T01:51:19,645+00:00 - info: Started checking updates from Tinder 
2017-07-29T01:51:19,674+00:00 - debug: Started Facebook Login for Tinder channel

I hope You can help me ;)

**Comment by hfreire** [comment]
From the log, it seems facebook-login-for-robots is timing out when authenticating. Release v1.2.76 containing commit 112160648d4933af2f93acec4f9655dcc01770bb increases this timeout.
