### ISSUE TITLE
404

### ISSUE THREAD

**Issue by pimboli** [hfreire/get-me-a-date#2298]
Hi,

after starting the docker command and accessing the webpage I get a 404 error.

http://x.x.x.x:5940/

Anyone an idea?

thanks

**Comment by pimboli** [comment]
I managed to start the docker in interactive mode and I get the following message:

`docker run -i -p "5940:3000" hfreire/get-me-a-date
info: Running version v1.3.569 from commit 596c4f9e0976d86148d2bd488039187ada0bc25d built on Thu Aug  6 03:30: 08 UTC 2020
(node:1) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
info: Started 🚀  HTTP server on port 3000
warn:  message=Database.channels.find is not a function, stack=TypeError: Database.channels.find is not a function
    at Tinder.createChannelIfNeeded (/home/node/get-me-a-date/src/channels/channel.js:37:28)
    at Tinder.init (/home/node/get-me-a-date/src/channels/channel.js:55:44)
    at /home/node/get-me-a-date/src/dates/channel.js:25:89
    at tryCatcher (/home/node/get-me-a-date/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/home/node/get-me-a-date/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/home/node/get-me-a-date/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/home/node/get-me-a-date/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/node/get-me-a-date/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/node/get-me-a-date/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/home/node/get-me-a-date/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/home/node/get-me-a-date/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/home/node/get-me-a-date/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/node/get-me-a-date/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/node/get-me-a-date/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:458:21)
warn:  message=[Breaker: defaultBrake] this._rekognition.listCollectionsAsync is not a function, stack=TypeError: this._rekognition.listCollectionsAsync is not a function
    at /home/node/get-me-a-date/src/utils/rekognition.js:52:131
    at /home/node/get-me-a-date/node_modules/bluebird-retry/lib/bluebird-retry.js:71:29
    at tryCatcher (/home/node/get-me-a-date/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/home/node/get-me-a-date/node_modules/bluebird/js/release/method.js:39:29)
    at try_once (/home/node/get-me-a-date/node_modules/bluebird-retry/lib/bluebird-retry.js:70:24)
    at tryCatcher (/home/node/get-me-a-date/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/node/get-me-a-date/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/node/get-me-a-date/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/node/get-me-a-date/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/node/get-me-a-date/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/node/get-me-a-date/node_modules/bluebird/js/release/promise.js:673:18)
    at Timeout._onTimeout (/home/node/get-me-a-date/node_modules/bluebird/js/release/timers.js:26:46)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)
info: Started finding dates
info: Started updating stats
info: Finished updating stats
info: Finished finding dates (time = 0s)`
