### ISSUE TITLE
Application not populating Tinder data

### ISSUE THREAD

**Issue by bane5000** [hfreire/get-me-a-date#880]
I've installed this on Ubuntu as well as Debian and neither work. I have tried both node versions 10 as well as 8.9.0. The result is the same, a blank screen shown here: https://snag.gy/YtnEMC.jpg (and yes the tinder channel is enabled in the upper left corner)

My environment is as follows:
FACEBOOK_USER_EMAIL=user@gmail.com
FACEBOOK_USER_PASSWORD=password
AWS_REGION=us-east-1
AWS_ACCESS_KEY_ID=keyid
AWS_SECRET_ACCESS_KEY=secret

Here are some interesting error messages when I issue 'container logs [containerid]':

2018-05-19T01:47:10,998+00:00 - error:  AssertionError [ERR_ASSERTION]: No node found for selector: input#email
    at Console.assert (console.js:188:23)
    at Frame.type (/opt/get-me-a-date/node_modules/puppeteer/lib/FrameManager.js:661:13)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
2018-05-19T01:47:10,999+00:00 - info: Finished checking recommendations from Tinder channel (received = 0, skipped = 0, failed = 0)
2018-05-19T01:47:11,000+00:00 - info: Started checking updates from Tinder
2018-05-19T01:48:54,434+00:00 - error:  Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/opt/get-me-a-date/node_modules/puppeteer/lib/NavigatorWatcher.js:73:21)
    at <anonymous>

Full log can be found here: https://pastebin.com/NQzZG434

Please advise

**Comment by bane5000** [comment]
Is this application working seamlessly for anyone else, or is it just me?

**Comment by Roozbehy** [comment]
exact same issue here

**Comment by erkkimon** [comment]
I am struggling with similar problems. It looks like the software fails to get Tinder accessToken. Any ideas how to work around this? It would be great to be able to enter accessToken as environment variable in case oAuth fails. By the way, why does it fail? ping @hfreire 

```
curl -X GET --header 'Accept: application/json' 'http://localhost:5940/channels'
[{"name":"tinder","isEnabled":true,"userId":"0","accessToken":null,"lastActivityDate":null,"isOutOfLikes":false,"outOfLikesDate":null,"createdAt":"2019-10-21T19:53:46.601Z","updatedAt":"2019-10-21T20:56:06.035Z"},{"name":"happn","isEnabled":false,"userId":"0","accessToken":null,"lastActivityDate":null,"isOutOfLikes":false,"outOfLikesDate":null,"createdAt":"2019-10-21T19:53:46.616Z","updatedAt":"2019-10-21T19:53:46.616Z"}]
```

**Comment by anoduck** [comment]
@hfreire  Please, help.
1. Is this app still supposed to be functioning?  
2. If so, why is it not populating any data?

I incorporated the use of docker-compose to set the environment variables for the docker image that was created and assumed all that was needed was to set the environmental variables and run the docker image. Is there something that I am missing?

**Comment by anoduck** [comment]
@all Anyone got this app working?
